Repository futurewei-cloud/alcor-control-agent, pull requests merged in 2020-10, with the labels that each got.

#140 [Documentation] Documents update based on latest implementation and script update
  README.md
  build/aca-machine-init.sh
  docs/images/Agent_components.jpg
  src/README.md
Labels: documentation

#143 Issue 142: build script and test cases
  build/aca-machine-init.sh
  src/ovs/aca_ovs_l2_programmer.cpp
Labels: Build-related, bug

#150 aca_memory_leak_test
  include/aca_grpc.h
  src/aca_main.cpp
  src/comm/aca_grpc.cpp
Labels: Zeta, enhancement

#133 ACA supports pulsar consumer
  build/Dockerfile
  build/Dockerfile.proxy
  build/aca-machine-init.sh
  include/aca_comm_mgr.h
  include/aca_message_pulsar_consumer.h
  include/aca_message_pulsar_producer.h
  src/CMakeLists.txt
  src/aca_main.cpp
  src/comm/aca_comm_mgr.cpp
  src/comm/aca_message_consumer.cpp
  src/comm/aca_message_pulsar_consumer.cpp
  src/comm/aca_message_pulsar_producer.cpp
  test/CMakeLists.txt
  test/func_tests/gs_tests.cpp
  test/gtest/aca_tests.cpp
Labels: Feature

#155 [Enhancement] Update the compiler option to: -Wall -Wextra -pedantic -Wpedantic -Werror
  CMakeLists.txt
  include/aca_dhcp_server.h
  include/aca_util.h
  src/aca_main.cpp
  src/comm/aca_comm_mgr.cpp
  src/comm/aca_grpc.cpp
  src/dhcp/aca_dhcp_server.cpp
  src/dhcp/aca_dhcp_state_handler.cpp
  src/dp_abstraction/aca_dataplane_ovs.cpp
  src/dp_abstraction/aca_goal_state_handler.cpp
  src/net_config/aca_net_config.cpp
  src/ovs/aca_ovs_control.cpp
  src/ovs/aca_ovs_l2_programmer.cpp
  src/ovs/aca_ovs_l3_programmer.cpp
  src/ovs/aca_vlan_manager.cpp
  src/ovs/ovs_control.cpp
  test/func_tests/gs_tests.cpp
  test/gtest/aca_test_dhcp.cpp
  test/gtest/aca_test_main.cpp
Labels: Zeta
